### ISSUE TITLE
when testing the minified menu on safari + iphone, menu items either don't work or take 2 taps to open

### ISSUE THREAD

**Issue by dncastilho** [amirkian007/vue-awesome-sidebar#9]
as per description

**Comment by amirkian007** [comment]
@dncastilho 
Hi , well that doesn't sound good, I can confirm that the bug is in fact real, looks like safari touch functionality works a bit different than chrom or Firefox, I will fix it ASAP and let you know when it's fixed.
Thanks for using this package BTW!

**Comment by dncastilho** [comment]
> @dncastilho Hi , well that doesn't sound good, I can confirm that the bug is in fact real, looks like safari touch functionality works a bit different than chrom or Firefox, I will fix it ASAP and let you know when it's fixed. Thanks for using this package BTW!

no- thank YOU for the awesome package and prompt support. this package saved me a lot of time and the resulting menu looks quite good!

**Comment by amirkian007** [comment]
@dncastilho 
I am glad to here that :)))

**Comment by amirkian007** [comment]
@dncastilho hi i fixed the problem and released a new version(1.2.2) and it works ok in ios 15.6.1 can you check ?

**Comment by dncastilho** [comment]
all good - the fix worked. thank you

**Comment by darkvertex** [comment]
I still have an issue on an ipad and android tablets.

I can also reproduce by going into Chrome Devtools, enabling Device Emulation to pretend to be a touch device and then clicking in the sidebar.

If the sidebar is wide, everything works fine. If the sidebar is collapsed to a thin state, I have to tap twice to go into a section. First tap widens the section title, second tab makes it go there. Is there a way to make it work with one tap on touchscreens?
